Output fieldset.gif
Set Theme "Catppuccin Mocha"
Set FontSize 32
Set Width 2400
Set Height 600
Set Framerate 30
Set Padding 20
Set PlaybackSpeed 2
Hide
Type "cargo build --example fieldset 2>/dev/null"
Enter
Sleep 5s
Type "cargo run --example fieldset 2>/dev/null"
Enter
Sleep 1s
Show
Sleep 1.5s
Type "l"
Sleep 1.5s
Type "l"
Sleep 1.5s
Type "l"
Sleep 1.5s
Type "l"
Sleep 1.5s
Type "l"
Sleep 1.5s
Type "l"
Sleep 1.5s
Type "q"
